export const theme = {
  fonts: {
    body: "system-ui, sans-serif",
    heading: '"Avenir Next", sans-serif',
    monospace: "Menlo, monospace",
  },
  colors: {
    bodyText: "#fff",
    text: "#000",
    highlightText: "DeepSkyBlue",
    highlightedText: "DeepSkyBlue",
    buttonBackground: "#fff",
    disabledButton: "#F3F4F3",
    boxesBackground: "#c2e9ff",
    mainBackground: "#e5e5e5",
    headerFooter: "DeepSkyBlue",
    plusStart: "DeepSkyBlue",
    minusPause: "coral",
    refresh: "lightgreen",
    selectedBackground: "DeepSkyBlue",
    primary: "#33e",
    modes: {
      dark: {
        bodyText: "#000",
        text: "#FFF",
        highlightText: "#0075a8",
        highlightedText: "#0075a8",
        buttonBackground: "#222",
        boxesBackground: "grey",
        mainBackground: "#000",
        headerFooter: "#343434",
        plusStart: "#001b56",
        minusPause: "#562100",
        refresh: "#007a02",
        selectedBackground: "#0075a8",
        primary: "#33e",
      },
    },
  },
  text: {
    title: {},
    default: {
      fontFamily: "Thaoma",
      fontSize: "30px",
      fontWeight: "bold",
    },
  },
};
